// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDo_Backend.Model;

namespace ToDo_Backend.Migrations
{
    [DbContext(typeof(ToDosContext))]
    partial class ToDosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("ToDo_Backend.Model.ToDo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Beschreibung")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Erledigt")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID");

                    b.ToTable("todos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Beschreibung = "Alle CRUD-Operatioen umsetzen",
                            Deadline = new DateTime(2022, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Erledigt = false,
                            Titel = "Webservice fertig implementieren"
                        },
                        new
                        {
                            ID = 2,
                            Beschreibung = "Sollte man eh immer machen :)",
                            Deadline = new DateTime(2022, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Erledigt = false,
                            Titel = "Mathe lernen"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
